name: generate_cat_entry

on:
  issues:
    types: labeled

jobs:
  build:
    if: ${{ github.event.label.name == 'good-to-go' }}
    runs-on: ubuntu-latest
    steps:
    - name: Set up environment
      run: |
        git config --global user.email "test@github.land"
        git config --global user.name "GitHub Almighty"

    - uses: actions/checkout@v3

    - uses: stefanbuck/github-issue-praser@v2
      id: issue-parser
      with:
        template-path: .github/ISSUE_TEMPLATE/add_dataset.yml
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Checkout datalad-catalog
      uses: actions/checkout@v3
      with:
        repository: datalad/datalad-catalog
        path: datalad-catalog
      
    - name: Install datalad-catalog
      run: |
        pip install -e datalad-catalog/

    - name: Checkout fairly-big-catalog-workflow
      uses: actions/checkout@v3
      with:
        repository: jsheunis/fairly-big-catalog-workflow
        path: fairly-big-catalog-workflow

    - name: Add subdataset
      run: |
        echo '${{ steps.issue-parser.outputs.jsonString }}'
        echo '${{ steps.issue-parser.outputs.jsonString }}' | jq '.url'
        VARURL=$(echo '${{ steps.issue-parser.outputs.jsonString }}' | jq '.url')
        echo '$VARURL'
        datalad datalad clone -d . '$VARURL'
        datalad save -m "adds dataset to catalog"
        datalad push --to github